language: erlang

otp_release:
  - 18.2

services:
  - docker

before_script:
  - set -e

script:
  - make
  - ./bin/mkimage
  - docker build \
       --build-arg REL_NAME=$(bin/release_name) \
       --build-arg ERTS_VSN=$(bin/system_version) \
       --pull=true \
       --no-cache=true \
       --force-rm=true \
       -t $(bin/release_name):$(bin/version) .
